In [1]:
%load_ext autoreload
%autoreload 1

import numpy as np
from squad_load import get_glove_train_embs, get_squad_train_voc, load_squad_train
from itertools import chain

%aimport QANet_wo_charemb
%aimport HRED_v2

WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 780 (CNMeM is enabled with initial size: 30.0% of memory, cuDNN 5105)


In [2]:
%%time
squad_path = '/pio/data/data/squad/'
glove_path = '/pio/data/data/glove_vec/6B/'

data = np.load(squad_path + 'train.pkl')
i_to_w, w_to_i, voc_size = get_squad_train_voc(squad_path)
glove_embs = get_glove_train_embs(squad_path, glove_path)

def get_w(idx):
    return i_to_w[idx]

# Some answers get broken in the process of tokenization, because some answer words are not properly split.
def filter_broken_answers(data):
    return [d for d in data if d[0]]

print 'Examples total:', len(data)

data = filter_broken_answers(data)

print 'Working examples:', len(data)

Examples total: 87599
Working examples: 86474
CPU times: user 9.23 s, sys: 546 ms, total: 9.77 s
Wall time: 9.77 s


In [3]:
# Originally contexts are split into sentences, this reverses that.
for i in xrange(len(data)):
    data[i].append(list(chain(*data[i][1][1:])))
    data[i][1] = data[i][1][0]

In [4]:
trim = 300
data = [d[:2] + [d[2][:trim]] for d in data if max(d[0][0]) < trim]
print 'Trimmed examples:', len(data)

Trimmed examples: 86355


In [5]:
data_dev = np.load(squad_path + 'dev_with_training_vocab.pkl')

In [6]:
# Originally contexts are split into sentences, this reverses that.
for i in xrange(len(data_dev)):
    data_dev[i].append(list(chain(*data_dev[i][1][1:])))
    data_dev[i][1] = data_dev[i][1][0]

## QANet

In [7]:
%%time
qa_net = QANet_wo_charemb.QANet(voc_size=voc_size,
                                emb_size=300,
                                rec_size=300,
                                emb_init=glove_embs)

Building the model...
Compiling theano functions...
Done
CPU times: user 58.7 s, sys: 1.8 s, total: 1min
Wall time: 59.7 s


In [144]:
# qa_net.load_params('test_params_3ep.npz')

In [8]:
# 1 ep

# dane są przycięte do długości 300 (jeśli odpowiedź się nie mieści, to pytanie jest usuwane z danych)
# przycięto około 1400 próbek, usunięto 119

# gdzie się da: glove init, reszta: losowo, trenujemy wszystkie słowa

qa_net.train_one_epoch(data, 20, log_interval=5)

Done 5 batches in 5.15s	training loss:	10.122009
Done 10 batches in 9.61s	training loss:	9.667361
Done 15 batches in 14.21s	training loss:	9.112970
Done 20 batches in 18.37s	training loss:	8.641973
Done 25 batches in 23.22s	training loss:	8.408045
Done 30 batches in 28.25s	training loss:	8.202090
Done 35 batches in 32.50s	training loss:	7.962139
Done 40 batches in 37.65s	training loss:	7.839150
Done 45 batches in 42.71s	training loss:	7.666236
Done 50 batches in 47.20s	training loss:	7.544918
Done 55 batches in 52.34s	training loss:	7.443301
Done 60 batches in 57.13s	training loss:	7.349420
Done 65 batches in 62.09s	training loss:	7.267830
Done 70 batches in 67.07s	training loss:	7.199441
Done 75 batches in 71.66s	training loss:	7.109486
Done 80 batches in 76.68s	training loss:	7.039987
Done 85 batches in 80.68s	training loss:	7.004878
Done 90 batches in 85.71s	training loss:	6.920982
Done 95 batches in 90.95s	training loss:	6.869086
Done 100 batches in 95.42s	training loss:	6.829583
D

3.4391028607963769

In [9]:
qa_net.save_params('test_params_1ep_simplified_lstm_fixed')

### QANet tests

In [10]:
def predict_spans(data, beam=10, batch_size=10):
    num_examples = len(data)
    
    start_probs = qa_net.get_start_probs(data, batch_size)
    best_starts = start_probs.argpartition(-beam, axis=1)[:, -beam:].astype(np.int32)
    
    scores = start_probs[np.arange(num_examples)[:, np.newaxis], best_starts]
    scores = np.tile(scores[:, np.newaxis], (beam, 1)).transpose(0, 2, 1)
    
    best_ends_all = []
    for i in xrange(beam):
        end_probs = qa_net.get_end_probs(data, best_starts[:, i], batch_size)
        best_ends = end_probs.argpartition(-beam, axis=1)[:, -beam:]
        scores[:, i, :] *= end_probs[np.arange(num_examples)[:, np.newaxis], best_ends]
        best_ends_all.append(best_ends)
        
    best_ends_all = np.hstack(best_ends_all)
        
    scores = scores.reshape(num_examples, beam**2)
    best_spans = scores.argmax(axis=1)
    starts = [i / beam for i in best_spans]
    
    starts = best_starts[np.arange(num_examples), starts]
    ends = best_ends_all[np.arange(num_examples), best_spans]
    
    return starts, ends

In [11]:
%%time
predicted_spans = []
batch_size = 10

idx = 0
while idx < len(data_dev):
    spans = predict_spans(data_dev[idx:idx + batch_size])
    predicted_spans.append(np.vstack(spans))
    idx += batch_size
    if not idx % 1000:
        print idx, 'examples'
        
print 'Predictions done'
    
predicted_spans = np.hstack(predicted_spans).T

1000 examples
2000 examples
3000 examples
4000 examples
5000 examples
6000 examples
7000 examples
8000 examples
9000 examples
10000 examples
Predictions done
CPU times: user 1h 14min 25s, sys: 2h 50min 59s, total: 4h 5min 25s
Wall time: 20min 49s


In [12]:
np.savez('evaluate/dev_with_training_vocab_predictions_lstm_fixed_1ep', predicted_spans)

In [181]:
'''
>>> python    evaluate-v1.1.py    dev-v1.1.json    dev_with_training_vocab_predictions.txt 
{"f1": 58.19603067603314, "exact_match": 47.74834437086093}
'''

'''po naprawieniu paddingu, 1ep lstm: "f1": 56.91212139901048, "exact_match": 46.96310312204352'''

CPU times: user 5.48 s, sys: 9.56 s, total: 15 s
Wall time: 1.27 s


(2, 20)

In [167]:
[d[0] for d in data_dev[120:140]]

[[[18, 19, 20], [18, 19, 20], [18, 19, 20]],
 [[29, 30, 31], [29, 30, 31], [29, 30, 31]],
 [[29, 30, 31], [29, 30, 31], [29, 30, 31, 32]],
 [[13, 14], [13, 14], [13, 14]],
 [[18, 19, 20], [18, 19, 20], [18, 19, 20]],
 [[10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31],
  [10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32],
  [10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32]],
 [[7], [7], [7]],
 [[10, 11], [10, 11], [10, 11, 12]],
 [[18, 19, 20], [18, 19, 20], [18, 19, 20]],
 [[24, 25], [24, 25], [24, 25, 26, 27, 28]],
 [[29, 30, 31, 32], [29, 30, 31], [29, 30, 31, 32]],
 [[18, 19, 20], [18, 19, 20], [18, 19, 20]],
 [[13, 14], [13, 14], [13, 14, 15]],
 [[29, 30, 31, 32], [29

In [169]:
idx = 24
map(get_w, data_dev[120][2][idx:idx + 5])

[u'san', u'francisco', u'bay', u'area', u"'s"]

In [148]:
res.argmax(axis=1)

array([ 14,  14,  71,  14,  94, 129,  60,  26, 129,  26,  60,  45,  85,
        71, 129,  22,  22,  71, 129, 129])

In [147]:
res.argpartition(-10, axis=1)[:, -10:]

array([[112,   5,  94, 129,  25,  26,  14,  13,  37,  85],
       [ 45,  36,  44,  85,  13, 129,  26,  37,  14,  94],
       [ 44,  14,  45,  85,  79,   6,  76,   5,  71,  66],
       [ 45,  44,  85,   5, 129,  13,  14,  26,  37,   0],
       [117,  90,  45, 129,   2,  94, 143,   5,   6, 116],
       [ 99,   6,   4,  85,  93,  94, 143, 129,  14,   5],
       [ 22,   0,   1,  71,  66,  63,  60,  85,  59,  61],
       [ 93,  85,  94,   1,  21,  14,  25,  26, 129,   0],
       [ 99,   6,   4,  85,  93,  94, 143, 129,  14,   5],
       [ 94,  99,  37,  27,  14, 129,   1,   0,  26,  25],
       [ 66,   1,  55, 129,  94,  63,  61,  60,  22,  85],
       [ 46,  33,  14,  37,  26,   5,  45,  66,  43,  44],
       [ 44,  71,  94,  85,  26,  14, 129,  45,  66,   5],
       [ 94,  33,  66,  71,  72,  76,  77,  79,  44,  45],
       [131, 112, 142, 143,  94, 122, 130, 137, 129, 128],
       [  6,  14,  23,  22,  13,  15,  21,  16,  20,   1],
       [ 18,  46,  85,  26,  30,  23,  22,  63,  45,  44

## HRED v2

In [4]:
hred_net = HRED(voc_size=voc_size,
                emb_size=300,
                lv1_rec_size=300,
                lv2_rec_size=300,
                out_emb_size=300,
                emb_init=glove_embs)

Building the model...
Compiling theano functions...
Done


In [5]:
ans = hred_net.get_output(data[:12], 3)
ans[0]

[array([ 0.6484955 ,  0.39728042,  0.29447019,  0.21638568,  0.34087649,
         0.42938796,  0.48248306,  0.45450044,  0.63264418], dtype=float32),
 array([ 0.43808964,  0.31143361,  0.32550314,  0.41264656,  0.40189919,
         0.67630386,  0.55489218,  0.2793248 ,  0.29060629,  0.52473378,
         0.40135068,  0.42928901,  0.24922398,  0.29269892,  0.26922536,
         0.37188664], dtype=float32),
 array([ 0.48105857,  0.35441753,  0.33231139,  0.33165267,  0.25691301,
         0.29037777,  0.38888532,  0.45136821,  0.26165053,  0.35437146,
         0.36461809,  0.29422539,  0.29016727,  0.75232959,  0.50326639,
         0.4879126 ,  0.19824371,  0.41686958,  0.44867724,  0.63904244,
         0.59564072,  0.3762525 ,  0.55565   ,  0.20368919,  0.45814279,
         0.13423204,  0.25729677,  0.28506696,  0.130806  ,  0.43678874], dtype=float32),
 array([ 0.36110905,  0.18258747,  0.213524  ,  0.28226432,  0.41397128,
         0.32674885,  0.29788589,  0.61358768,  0.34168947,  0.22

In [12]:
list(chain(*ans[8]))[46]

0.05232447

In [11]:
get_w(list(chain(*data[8][1][1:]))[45])

u'september'

In [10]:
list(reversed(np.array(list(chain(*ans[8]))).argsort()))

[46,
 23,
 45,
 74,
 7,
 19,
 49,
 8,
 6,
 126,
 10,
 24,
 28,
 80,
 9,
 29,
 54,
 43,
 31,
 37,
 4,
 42,
 123,
 82,
 11,
 30,
 111,
 94,
 16,
 35,
 81,
 15,
 50,
 148,
 62,
 78,
 53,
 91,
 204,
 33,
 13,
 12,
 105,
 21,
 20,
 155,
 152,
 122,
 36,
 158,
 125,
 203,
 217,
 5,
 22,
 84,
 14,
 87,
 27,
 34,
 3,
 85,
 107,
 222,
 186,
 79,
 25,
 110,
 128,
 56,
 175,
 60,
 127,
 131,
 52,
 117,
 63,
 149,
 112,
 47,
 26,
 66,
 55,
 2,
 32,
 86,
 197,
 171,
 151,
 61,
 108,
 83,
 137,
 119,
 124,
 48,
 67,
 166,
 201,
 134,
 239,
 1,
 172,
 44,
 236,
 90,
 233,
 106,
 77,
 240,
 104,
 176,
 71,
 141,
 75,
 0,
 227,
 142,
 101,
 109,
 198,
 147,
 202,
 154,
 73,
 207,
 18,
 235,
 226,
 93,
 65,
 59,
 150,
 120,
 194,
 113,
 195,
 205,
 121,
 118,
 153,
 57,
 232,
 39,
 17,
 216,
 132,
 41,
 140,
 247,
 116,
 178,
 64,
 97,
 179,
 100,
 58,
 224,
 76,
 170,
 70,
 69,
 51,
 243,
 103,
 133,
 169,
 136,
 218,
 237,
 238,
 143,
 72,
 174,
 167,
 102,
 225,
 177,
 200,
 89,
 181,
 114,
 146,
 20

In [ ]:
# Zwykły trening nie robił nic: wartości zwracane przez sieć dla zbioru uczącego nie miały żadnego sensu.
# Największe prawdopodobieństwa były prawie niezależne od pytania, miało ono mały wpływ na to, co się dzieje.
# Dla kosztu weighted_bin_ce mocno skrzywionego w stronę sytuacji t=1 wyszło podobnie.
#
# Następny krok: użyć zanurzeń GloVe, dodać cechy z https://arxiv.org/abs/1703.04816
#
# UPDATE:
# Obie cechy podobieństwa kontekstu do pytania dodane.
# W glove.6B jest około 70% słów ze zbioru uczącego SQuAD.
# W tej chwili te wektory biorę z glove.6B.300d, a pozostałym daję losowy init, 
# po czym wszystkie zanurzenia są dalej uczone.

In [6]:
hred_net.train_one_epoch(data_trimmed, 5, log_interval=20) # weighted cost, random init

Done 20 batches in 7.96s	training loss:	0.813393
Done 40 batches in 16.89s	training loss:	0.618499
Done 60 batches in 25.51s	training loss:	0.537964
Done 80 batches in 33.72s	training loss:	0.476587
Done 100 batches in 41.79s	training loss:	0.436442
Done 120 batches in 48.56s	training loss:	0.419979
Done 140 batches in 57.10s	training loss:	0.409618
Done 160 batches in 65.07s	training loss:	0.408088
Done 180 batches in 74.05s	training loss:	0.397444
Done 200 batches in 81.68s	training loss:	0.401948
Done 220 batches in 90.27s	training loss:	0.401396
Done 240 batches in 98.95s	training loss:	0.410639
Done 260 batches in 107.43s	training loss:	0.418680
Done 280 batches in 115.18s	training loss:	0.427639
Done 300 batches in 123.33s	training loss:	0.426674
Done 320 batches in 131.00s	training loss:	0.422292
Done 340 batches in 139.84s	training loss:	0.424456
Done 360 batches in 148.91s	training loss:	0.415105
Done 380 batches in 156.67s	training loss:	0.416838
Done 400 batches in 163.90s	t

KeyboardInterrupt: 

In [5]:
hred_net.train_one_epoch(data_trimmed, 5, log_interval=20) # normal binary cross-entropy with random init

Done 20 batches in 2.25s	training loss:	0.228349
Done 40 batches in 5.03s	training loss:	0.154742
Done 60 batches in 7.65s	training loss:	0.126147
Done 80 batches in 10.05s	training loss:	0.106807
Done 100 batches in 12.52s	training loss:	0.095184
Done 120 batches in 14.64s	training loss:	0.090502
Done 140 batches in 17.25s	training loss:	0.087078
Done 160 batches in 19.51s	training loss:	0.085557
Done 180 batches in 22.31s	training loss:	0.082334
Done 200 batches in 24.40s	training loss:	0.082256
Done 220 batches in 26.96s	training loss:	0.081215
Done 240 batches in 29.60s	training loss:	0.082376
Done 260 batches in 32.51s	training loss:	0.083784
Done 280 batches in 34.97s	training loss:	0.084956
Done 300 batches in 37.36s	training loss:	0.084330
Done 320 batches in 39.52s	training loss:	0.083391
Done 340 batches in 42.24s	training loss:	0.083563
Done 360 batches in 44.99s	training loss:	0.081207
Done 380 batches in 47.14s	training loss:	0.081512
Done 400 batches in 49.09s	training lo

KeyboardInterrupt: 

In [6]:
hred_net.train_one_epoch(data_trimmed, 5, log_interval=20) # normal binary cross-entropy with glove init

Done 20 batches in 2.66s	training loss:	0.247073
Done 40 batches in 5.97s	training loss:	0.187469
Done 60 batches in 9.10s	training loss:	0.148785
Done 80 batches in 11.96s	training loss:	0.123427
Done 100 batches in 14.91s	training loss:	0.108109
Done 120 batches in 17.43s	training loss:	0.102956
Done 140 batches in 20.55s	training loss:	0.097911
Done 160 batches in 23.25s	training loss:	0.095246
Done 180 batches in 26.59s	training loss:	0.090887
Done 200 batches in 30.07s	training loss:	0.090136
Done 220 batches in 33.13s	training loss:	0.088647
Done 240 batches in 36.28s	training loss:	0.089258
Done 260 batches in 39.74s	training loss:	0.091964
Done 280 batches in 42.68s	training loss:	0.093008
Done 300 batches in 45.52s	training loss:	0.091937
Done 320 batches in 48.11s	training loss:	0.090498
Done 340 batches in 51.34s	training loss:	0.090224
Done 360 batches in 54.62s	training loss:	0.087337
Done 380 batches in 57.19s	training loss:	0.087323
Done 400 batches in 59.53s	training lo

KeyboardInterrupt: 

In [ ]:
hred_net.save_params()